# Generated by Django 5.2.9 on 2025-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Fundador', 'Fundador'), ('Administrador', 'Administrador'), ('Moderador', 'Moderador'), ('Editor', 'Editor'), ('Desarrollador', 'Desarrollador'), ('Diseñador', 'Diseñador'), ('Miembro', 'Miembro')], help_text='Selecciona tu rol en el equipo', max_length=100),
        ),
    ]
