# Generated by Django 5.0.3 on 2024-04-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0003_rename_mangas_manga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='Fechas',
            new_name='fecha_de_carga',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='mangas',
            new_name='nombre_del_manga',
        ),
    ]
