# Generated by Django 5.0.3 on 2024-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0005_manga_publicado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='publicado_por',
            field=models.CharField(default='No definido', max_length=100, verbose_name='publicado_por'),
        ),
    ]
