# Generated by Django 5.0.3 on 2024-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0006_alter_manga_publicado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Archivo',
            field=models.FileField(blank='True', upload_to='', verbose_name='Archivo_de_manga'),
        ),
        migrations.AddField(
            model_name='manga',
            name='portada_del_manga',
            field=models.ImageField(blank=True, upload_to='', verbose_name='portada'),
        ),
    ]
