# Generated by Django 5.0.3 on 2024-05-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0007_manga_archivo_manga_portada_del_manga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='portada_del_manga',
            new_name='front_page',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='Archivo',
        ),
        migrations.AddField(
            model_name='manga',
            name='manga_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Archivo_de_manga'),
        ),
    ]
