# Generated by Django 5.0.3 on 2024-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0008_rename_portada_del_manga_manga_front_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='publicado_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='publicado_por'),
        ),
    ]
