# Generated by Django 5.0.3 on 2024-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0009_alter_manga_publicado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Prueba', 'Prueba1')], default='Prueba', help_text='Agregar el género del manga', max_length=100, verbose_name='Géneros de mangas'),
        ),
    ]
