# Generated by Django 5.0.3 on 2024-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0011_alter_manga_type_of_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='front_page',
            field=models.ImageField(blank=True, null=True, upload_to='front_pages', verbose_name='portada'),
        ),
    ]
