# Generated by Django 5.0.3 on 2024-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0012_alter_manga_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='calificacion_promedio',
            field=models.DecimalField(db_column='calificacion', decimal_places=2, default=0.0, max_digits=3, verbose_name='calificacion'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='fecha_de_carga',
            field=models.DateField(db_column='Fecha', max_length=100, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='front_page',
            field=models.ImageField(blank=True, db_column='portada', null=True, upload_to='front_pages', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_file',
            field=models.FileField(blank=True, db_column='Archivo', null=True, upload_to='', verbose_name='Archivo_de_manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='nombre_del_manga',
            field=models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre_del_manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='publicado_por',
            field=models.CharField(blank=True, db_column='autor', max_length=100, null=True, verbose_name='Autor del manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Accion', 'Acción'), ('Aventura', 'Aventura')], db_column='Genero', default='Accion', help_text='Agregar el género del manga', max_length=100, null=True, verbose_name='Género del manga'),
        ),
    ]
