# Generated by Django 5.0.6 on 2024-06-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0012_alter_manga_calificacion_promedio_and_more'),
        ('webcomics', '0013_alter_manga_calificacion_promedio_and_more'),
    ]

    operations = [
    ]
