# Generated by Django 5.0.3 on 2024-06-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0014_merge_20240604_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_file',
            field=models.FileField(blank=True, db_column='Archivo', null=True, upload_to='', verbose_name='Archivo del manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='nombre_del_manga',
            field=models.CharField(db_column='nombre', max_length=100, unique=True, verbose_name='Nombre del manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='publicado_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='publicado_por'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Accion', 'Acción'), ('Aventura', 'Aventura')], default=('Accion', 'Acción'), help_text='Agregar el género del manga', max_length=10, verbose_name='Género del manga'),
        ),
        migrations.AlterModelTable(
            name='manga',
            table='Mangas',
        ),
    ]
