# Generated by Django 5.0.3 on 2024-06-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0015_alter_manga_manga_file_alter_manga_nombre_del_manga_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='manga',
            table_comment='\nTabla para la gestión de mangas en la base de datos.\n        ',
        ),
    ]
