# Generated by Django 5.0.3 on 2024-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0017_alter_manga_fecha_de_carga_alter_manga_front_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_file',
            field=models.FileField(blank=True, db_column='archivo', null=True, upload_to='', verbose_name='Archivo del manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Accion', 'Acción'), ('Aventura', 'Aventura')], db_column='genero del manga', default=('Accion', 'Acción'), help_text='Agregar el género del manga', max_length=10, verbose_name='Género del manga'),
        ),
    ]
