# Generated by Django 5.0.6 on 2024-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0019_alter_manga_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Accion', 'Acción'), ('Aventura', 'Aventura')], db_column='genero del manga', default=('Accion', 'Acción'), help_text='Agregar el género del manga', max_length=25, verbose_name='Género del manga'),
        ),
    ]
