# Generated by Django 6.0 on 2025-12-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0020_alter_manga_type_of_manga_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Denim Tears', 'Denim Tears'), ('Essentials', 'Essentials'), ('Porsche 911', 'Porsche 911')], db_column='genero del manga', default=('Denim Tears', 'Denim Tears'), help_text='Agregar el género del manga', max_length=100, verbose_name='Género del manga'),
        ),
    ]
