# Generated by Django 5.0.6 on 2024-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0021_alter_manga_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='front_page',
            field=models.ImageField(blank=True, db_column='portadas', upload_to='front_pages/', verbose_name='portada'),
        ),
    ]
