# Generated by Django 5.0.6 on 2024-06-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0022_alter_manga_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='front_page',
            field=models.ImageField(blank=True, db_column='portadas', upload_to='webcomics/staic/front_pages/', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Accion', 'Acción'), ('Aventura', 'Aventura')], db_column='genero del manga', default=('Accion', 'Acción'), help_text='Agregar el género del manga', max_length=100, verbose_name='Género del manga'),
        ),
    ]
