# Generated by Django 6.0 on 2025-12-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0022_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripción'),
        ),
    ]
