# Generated by Django 5.2.9 on 2025-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0023_manga_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
