# Generated by Django 5.2.9 on 2025-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0024_manga_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
