# Generated by Django 5.2.9 on 2025-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0025_manga_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Almacén')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
