# Generated by Django 5.2.9 on 2025-12-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0026_warehouseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Adquisición'),
        ),
    ]
