# Generated by Django 5.2.9 on 2025-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0027_manga_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Venta'),
        ),
    ]
