# Generated by Django 5.2.9 on 2025-12-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0029_warehouseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentry',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_entries', to='webcomics.manga'),
        ),
    ]
