# Generated by Django 5.2.9 on 2025-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0030_warehouseentry_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='depth_map',
            field=models.ImageField(blank=True, db_column='depth_map', null=True, upload_to='depth_maps/', verbose_name='Mapa de Profundidad'),
        ),
        migrations.AddField(
            model_name='manga',
            name='is_3d_converted',
            field=models.BooleanField(default=False, verbose_name='Convertido a 3D'),
        ),
    ]
