# Generated by Django 5.2.9 on 2025-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0031_manga_depth_map_manga_is_3d_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='back_depth_map',
            field=models.ImageField(blank=True, db_column='back_depth_map', null=True, upload_to='depth_maps/', verbose_name='Mapa de Profundidad Trasero'),
        ),
        migrations.AddField(
            model_name='manga',
            name='back_image',
            field=models.ImageField(blank=True, db_column='back_image', null=True, upload_to='back_pages/', verbose_name='Parte Trasera'),
        ),
    ]
