# Generated by Django 5.2.9 on 2025-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0032_manga_back_depth_map_manga_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='mesh_3d',
            field=models.FileField(blank=True, null=True, upload_to='meshes_3d/'),
        ),
    ]
