# Generated by Django 5.2.9 on 2025-12-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0033_manga_mesh_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='back_depth_map',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='back_image',
        ),
    ]
