# Generated by Django 5.2.9 on 2025-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0034_remove_manga_back_depth_map_remove_manga_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='talla',
            field=models.CharField(blank=True, help_text='Ej: S, M, L, XL o Talla de calzado', max_length=50, null=True, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='type_of_manga',
            field=models.CharField(blank=True, choices=[('Denim Tears', 'Denim Tears'), ('Essentials', 'Essentials'), ('Dandy Hats', 'Dandy Hats'), ('Barbas Hats', 'Barbas Hats')], db_column='genero del manga', default=('Denim Tears', 'Denim Tears'), help_text='Agregar el género del manga', max_length=100, verbose_name='Género del manga'),
        ),
    ]
