# Generated by Django 5.2.9 on 2026-01-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0036_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='MangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manga_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webcomics.manga')),
            ],
        ),
    ]
