# Generated by Django 5.2.9 on 2026-01-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0039_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_dm',
            field=models.BooleanField(default=False, verbose_name='Es Mensaje Directo'),
        ),
    ]
