# Generated by Django 5.0.3 on 2024-04-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangas', models.CharField(max_length=100, unique=True, verbose_name='Mangas')),
                ('Fecha', models.DateField(max_length=100, verbose_name='Fecha de carga')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
