# Generated by Django 5.0.3 on 2024-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangas',
            old_name='Fecha',
            new_name='Fechas',
        ),
        migrations.AlterField(
            model_name='mangas',
            name='mangas',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre_del_manga'),
        ),
    ]
