# Generated by Django 5.0.3 on 2024-04-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0002_rename_fecha_mangas_fechas_alter_mangas_mangas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mangas',
            new_name='Manga',
        ),
    ]
