# Generated by Django 5.0.3 on 2024-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomics', '0004_rename_fechas_manga_fecha_de_carga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='publicado_por',
            field=models.CharField(default='None', max_length=100, verbose_name='publicado_por'),
        ),
    ]
